### PR TITLE
Issue# 311 : Setting up proper content type while uploading image/file to Azure blob storage

### PR DESCRIPTION
**Pull request by SunilParisi123**
https://github.com/grandnode/grandnode2/issues/311

Proper content type missing while uploading image to blob storage causing image rendering issue when used in PDF generation.
When we upload image to azure blob storage, content type was not getting set properly. It's getting default to application/octet-stream and this is causing issue when we use these pictures in PDF generation or browse in browser(When we browse URL instead of rendering image it's getting downloaded). Setting up content type for each file helps in rendering the image in browser instead of default download and also rendering in PDF properly.

### CODE REVIEW

**Comment by KrzysztofPajak** [comment]
@SunilParisi123 Is blobHttpHeaders can be set in UploadBlob ?

**Comment by SunilParisi123** [comment]
> UploadBlob

No. When we use container client we can't set that for UploadBlob. We set only for the blobclient.Upload. Please find the example below.

https://stackoverflow.com/questions/10040403/set-content-type-of-media-files-stored-on-blob

var blobServiceClient = new BlobServiceClient("YOURCONNECTIONSTRING");
var containerClient = blobServiceClient.GetBlobContainerClient("YOURCONTAINERNAME");
var blob = containerClient.GetBlobClient("YOURFILE.jpg");

var blobHttpHeader = new BlobHttpHeaders { ContentType = "image/jpeg" };
 
var uploadedBlob = await blob.UploadAsync(YOURSTREAM, new BlobUploadOptions { HttpHeaders = blobHttpHeader });

**Comment by KrzysztofPajak** [comment]
To get content type please use IMimeMappingService.

**Comment by SunilParisi123** [comment]
> To get content type please use IMimeMappingService.

Get Mime type Updated with IMimeMappingService. Please review.

**Comment by SunilParisi123** [comment]
@KrzysztofPajak Can you review and merge this.

**Comment by KrzysztofPajak** [comment]
@SunilParisi123 MimeMappingService shold be used only in class AzurePictureService, why was used in PictureService?

**Comment by SunilParisi123** [comment]
> @SunilParisi123 MimeMappingService shold be used only in class AzurePictureService, why was used in PictureService?

I thought we may required in future to utilize in other inherited classes like AmazonPictureService, So injected at base class PictureService.
As of now it will not be required, so removed it from the other places except AzurePictureService. Please review now.

**Comment by KrzysztofPajak** [comment]
Thanks, if you didn't change anything in PictureService.cs please remove that changes

**Comment by SunilParisi123** [comment]
> Thanks, if you didn't change anything in PictureService.cs please remove that changes
@KrzysztofPajak : I have reverted the PictureService.cs changes. Please check now.

**Pull request merged**
