### PR TITLE
Azure blob thumbnail

### LINKED ISSUE #242: Thumbnails are not displaying if Azure blob configured
If azure blob details are configured, the thumb files are not getting written to blob storage

### PR DESCRIPTION
**Pull request by Nikhil13x**
Resolves #242   
Type: **|bugfix|**

## Issue
When the thumbnail url is returned, its not checking if the blob is really present. Hence the new thumbnails are never created.

## Solution
check if the blob exists before returning its URL. If not existing, return empty string. So that the picture service will create new thumbnail.

## Breaking changes
None

## Testing
1. Test with Azure blob configuration

### CODE REVIEW

**Comment by KrzysztofPajak** [comment]
@Nikhil13x  Please push only one file [AzurePictureService.cs](https://github.com/grandnode/grandnode2/pull/243/files#diff-52fdeb8efa250e00e6830450551dbbf7a9b07954300c8f265781cb423ac5b2d2)[AzurePictureService.cs](https://github.com/grandnode/grandnode2/pull/243/files#diff-52fdeb8efa250e00e6830450551dbbf7a9b07954300c8f265781cb423ac5b2d2)

**Comment by KrzysztofPajak** [comment]
@Nikhil13x  Please push only one file [AzurePictureService.cs](https://github.com/grandnode/grandnode2/pull/243/files#diff-52fdeb8efa250e00e6830450551dbbf7a9b07954300c8f265781cb423ac5b2d2)[AzurePictureService.cs](https://github.com/grandnode/grandnode2/pull/243/files#diff-52fdeb8efa250e00e6830450551dbbf7a9b07954300c8f265781cb423ac5b2d2)

**Comment by Nikhil13x** [comment]
> @Nikhil13x Please push only one file [AzurePictureService.cs](https://github.com/grandnode/grandnode2/pull/243/files#diff-52fdeb8efa250e00e6830450551dbbf7a9b07954300c8f265781cb423ac5b2d2)[AzurePictureService.cs](https://github.com/grandnode/grandnode2/pull/243/files#diff-52fdeb8efa250e00e6830450551dbbf7a9b07954300c8f265781cb423ac5b2d2)

Updated the PR.

**Comment by KrzysztofPajak** [comment]
@Nikhil13x 
Method blobClient.Exists() can be Async so it's better to use it.
And the last thing I would like to think about add the result of method blobClient.Exists()  to the Cache.

**Comment by KrzysztofPajak** [comment]
@Nikhil13x 
There is no need to use "await Task.FromResult" in thumbFile

**Pull request merged**
