### PR TITLE
escaping special character before passing the string to pdf scryber

### PR DESCRIPTION
**Pull request by eliyasbaby**
Resolves #issueNumber  
Type: **feature|bugfix|**

## Issue
Description of the issue this PR is solving, why it's happening, and how to reproduce it.

## Solution
Summarize your solution to the problem. Please include short description.

## Breaking changes
If you have a breaking changes, list them here, otherwise list none.

## Testing
1. List the steps needed for testing your PR.
2. Assume that everyone already know how to run the GrandNode, and do the basic configuration.
3. Be detailed enough that someone can work through it easily.

### CODE REVIEW

**Comment by KrzysztofPajak** [comment]
Hi @eliyasbaby 
This problem does not appears on develop version.
When my product name is: Redmi K30 Ultra \"   '    &   <  dsfg < sgd >
I can still generate PDF doc.
Could you share more information?

**Comment by eliyasbaby** [comment]
Actually its not for the product name, for me its failing when the item.AttributeDescription in orderPdfTemplate.cshtml contains PRO Engine: 7" Blade & Liner like that.

**Comment by KrzysztofPajak** [comment]
@eliyasbaby the problem is with <SMALL> HTML Tag.

**Comment by KrzysztofPajak** [comment]
Please check this commit https://github.com/grandnode/grandnode2/commit/18ec5d1401497c170f735679fce59893edd04335

**Pull request closed without merging**
