### PR TITLE
Issue# 314: Adding Asterisk (*) next to a form control label for Required fields when it generated through AdminLabelTagHelper

### PR DESCRIPTION
**Pull request by SunilParisi123**
…ired fields

Adding Asterisk (*) next to a form control label for Required fields when it generated through AdminLabelTagHelper

Resolves #issueNumber  
Type: **feature|bugfix|**

## Issue
Description of the issue this PR is solving, why it's happening, and how to reproduce it.

## Solution
Summarize your solution to the problem. Please include short description.

## Breaking changes
If you have a breaking changes, list them here, otherwise list none.

## Testing
1. List the steps needed for testing your PR.
2. Assume that everyone already know how to run the GrandNode, and do the basic configuration.
3. Be detailed enough that someone can work through it easily.

### CODE REVIEW

**Comment by SunilParisi123** [comment]
We can use it in admin-label tag as below:
<admin-label asp-for="Email" **asp-required="true"**/>

**Comment by Nikhil13x** [comment]
@KrzysztofPajak Do you consider this as a requirement? or any suggestion to handle this requirement?

**Comment by KrzysztofPajak** [comment]
@Nikhil13x, the idea is great and thanks, could you check how it looks with RTL language?

**Comment by SunilParisi123** [comment]
> @Nikhil13x, the idea is great and thanks, could you check how it looks with RTL language?

We have updated RTL css also now to support RTL language. At the end of the label asterisk (*) symbol will get displayed.

**Comment by SunilParisi123** [comment]
@KrzysztofPajak  Can you check this now. Added RTL support also.

**Comment by KrzysztofPajak** [comment]
Thanks for contributing!

**Pull request merged**
